# Generated by Django 2.0.2 on 2019-02-22 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0002_post_liked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='liked',
            new_name='liked_users',
        ),
    ]
